platform :ios, '4.3'
pod 'JSONKit',                 '~> 1.4'
pod 'Reachability',            '~> 3.0.0'
pod 'AFNetworking',            '~> 0.10'
pod 'DCKeyValueObjectMapping', '= 1.1'
pod 'MBProgressHUD',           '~> 0.5'
pod 'ActionSheetPicker',       '~> 0.0'
pod 'ECSlidingViewController', '~> 0.9.0'

target :MXNSlidingBoilerplateTests do
  pod 'Kiwi'
end
